"""empty message

Revision ID: 1356095d13de
Revises: b9658def0c33
Create Date: 2020-03-27 11:48:02.375295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1356095d13de'
down_revision = 'b9658def0c33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('essay1713', sa.Column('time', sa.String(length=32), nullable=True))
    op.add_column('essay1734', sa.Column('time', sa.String(length=32), nullable=True))
    op.add_column('essay1735', sa.Column('time', sa.String(length=32), nullable=True))
    op.add_column('essay1736', sa.Column('time', sa.String(length=32), nullable=True))
    op.add_column('essay1737', sa.Column('time', sa.String(length=32), nullable=True))
    op.add_column('essay1754', sa.Column('time', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('essay1754', 'time')
    op.drop_column('essay1737', 'time')
    op.drop_column('essay1736', 'time')
    op.drop_column('essay1735', 'time')
    op.drop_column('essay1734', 'time')
    op.drop_column('essay1713', 'time')
    # ### end Alembic commands ###
