"""empty message

Revision ID: 3ac62b6352ce
Revises: 
Create Date: 2020-03-02 16:49:12.375663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ac62b6352ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_studyroom_jc', table_name='studyroom')
    op.drop_index('ix_studyroom_js', table_name='studyroom')
    op.drop_index('ix_studyroom_xqs', table_name='studyroom')
    op.drop_index('ix_studyroom_zc', table_name='studyroom')
    op.drop_table('studyroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studyroom',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('zc', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('xqs', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('jc', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('js', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('studyroom', mysql.TEXT(), nullable=True),
    sa.Column('updata_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_studyroom_zc', 'studyroom', ['zc'], unique=False)
    op.create_index('ix_studyroom_xqs', 'studyroom', ['xqs'], unique=False)
    op.create_index('ix_studyroom_js', 'studyroom', ['js'], unique=False)
    op.create_index('ix_studyroom_jc', 'studyroom', ['jc'], unique=False)
    # ### end Alembic commands ###
