"""empty message

Revision ID: b9658def0c33
Revises: b9a95659df94
Create Date: 2020-03-21 18:47:02.786920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9658def0c33'
down_revision = 'b9a95659df94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay1713',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay1735',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay1736',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay1737',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay1754',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay1754')
    op.drop_table('essay1737')
    op.drop_table('essay1736')
    op.drop_table('essay1735')
    op.drop_table('essay1713')
    # ### end Alembic commands ###
