"""empty message

Revision ID: b9a95659df94
Revises: 79c787a1457c
Create Date: 2020-03-19 19:04:53.250988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a95659df94'
down_revision = '79c787a1457c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay1734',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('essayid', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=128), nullable=True),
    sa.Column('updata_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay1734')
    # ### end Alembic commands ###
